version: '3.9'

services:
  app:
    build: ./php
    volumes:
      - ./src:/data

  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./src:/data
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8080:80
    depends_on:
      - db
    restart: always

  db:
    build: ./mysql
    ports:
      - 3309:3306
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store: